FROM python:3.6
WORKDIR /opentalents
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY . /opentalents
RUN apt-get update && apt-get install -y xvfb wkhtmltopdf graphviz 
    build-essential \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info
RUN pip install -r requirements.txt
