# FROM python:3.6
# WORKDIR /opentalents
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1
# COPY . /opentalents
# RUN apt-get update && apt-get install -y xvfb wkhtmltopdf graphviz  
# RUN pip install -r requirements.txt
# RUN apt-get update && apt-get install -y cron
FROM python:3.6
WORKDIR /opentalents
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY . /opentalents
RUN apt-get update && apt-get install -y xvfb graphviz wget xfonts-75dpi fontconfig
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
RUN dpkg -i wkhtmltox_0.12.5-1.buster_amd64.deb
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y cron