"""
Django settings for SMS project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from django.contrib.messages import constants as messages
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# images directory
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
'''
with open('C:/Users/User/Desktop/secret/secret_key.txt', encoding='utf8') as f:
    SECRET_KEY = f.read().strip()


with open('C:/Users/User/Desktop/secret/database_password.txt', encoding='utf8') as f:
    DATABASE_PASSWORD = f.read().strip()
'''
SECRET_KEY = 'admin'
DATABASE_PASSWORD = 'admin'

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# ALLOWED_HOSTS = ['localhost','127.0.0.1']
ALLOWED_HOSTS = ['*']
PROTOCOLE_HOST = "http://localhost:8000"
# EMAIL
EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
EMAL_HOST = 'localhost'
EMAIL_HOST_USER = 'user'
'''
with open('C:/Users/User/Desktop/secret/email_host_password.txt', encoding='utf8') as f:
    EMAIL_HOST_PASSWORD = f.read().strip()
'''

EMAIL_HOST_PASSWORD = '???'
EMAIL_PORT = 587

# EMAIL_ENABLED = True to activate sending emails
EMAIL_ENABLED = True

STAFF_EMAILS = {
    'scolarite': ['scolarite@univ.dz'],
    'direction': ['direction@univ.dz'],
    'stage': ['stage@univ.dz'],
    'futurs_stagiaires': ['futurs_stagiaires@univ.dz'],
    'webmaster': ['webmaster@univ.dz']
}

ADMINS = (
    ('Admin', 'admin@univ.dz'),
)

# google AGENDA parameters
SCOPES = ["https://www.googleapis.com/auth/calendar"]
# GOOGLE_CLIENT_SECRET_FILE="C:/Users/User/Desktop/secret/code_secret_client_fet.json"
GOOGLE_CLIENT_SECRET_FILE = "test"

# SMS PROVIDER SETTINGS
SMS_ENABLED = False
SMS_URL = 'https://wsp.sms-algerie.com/api/json'
SMS_API_KEY = '??'
SMS_USER_KEY = '??'

# Application definition

INSTALLED_APPS = [
    'scolar.apps.ScolarConfig',
    'django_tables2',
    'django_filters',
    'crispy_forms',
    'jquery',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    'social_django',
    'jchart',
    'django_icons',
    'wkhtmltopdf',
    'django_ajax',
    'django_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'rest_framework',
    'django_cleanup.apps.CleanupConfig',
    'captcha',
]

DATE_INPUT_FORMATS = ['%d/%m/%Y']
CRISPY_TEMPLATE_PACK = 'bootstrap4'

TIME_INPUT_FORMATS = ['%I:%M %p']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'SMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'social_django.context_processors.backends',  # social_django
                'social_django.context_processors.login_redirect',  # social_django
                'scolar.context_processors.institution',  # default context institution info
            ],
        },
    },
]

BOOTSTRAP4 = {
    'include_jquery': True,
}

WSGI_APPLICATION = 'SMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'scolar', 'migrations', 'db.sqlite3'),
        'ATOMIC_REQUESTS': True,
    }

}

# Login
LOGIN_URL = '/accounts/login'
LOGOUT_REDIRECT_URL = '/scolar/index'
LOGIN_REDIRECT_URL = '/scolar/index'

AUTH_USER_MODEL = 'scolar.User'

AUTHENTICATION_BACKENDS = (  # enable authentication against two backends Google and Model
    'axes.backends.AxesBackend',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# social django features and auth strategy
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    # Associates the current social details with another user account with
    # a similar email address. Disabled by default.
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# Il faut créer un client google oauth pour activer l'authetification via google
SOCIAL_AUTH_STRATEGY = 'social_django.strategy.DjangoStrategy'  # new
SOCIAL_AUTH_STORAGE = 'social_django.models.DjangoStorage'  # new
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1073618534328-lvqj7aj4htr03vpl9d6fdn7cg9tmffqr.apps.googleusercontent.com'  # new
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'  # new
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['state']

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Algiers'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'root')
STATICFILES_DIRS = [
    #    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]

# security settings
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = False
# SECURE_HSTS_SECONDS = 3600
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_SSL_HOST = 'talents.univ.dz'
# SECURE_SSL_REDIRECT = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# X_FRAME_OPTIONS = 'SAMEORIGIN'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = False
# SESSION_COOKIE_SAMESITE = None

# WKHTMLTOPDF_CMD = 'xvfb-run -a wkhtmltopdf'
WKHTMLTOPDF_CMD = 'C:/Program\ Files/wkhtmltopdf/bin/wkhtmltopdf.exe --enable-local-file-access'

# WKHTMLTOPDF_CMD = 'C:/Program\ Files/wkhtmltopdf/bin/wkhtmltopdf.exe --enable-local-file-access --disable-smart-shrinking --zoom 0.45'

# REGEX_MATRICULE='\d\d/\d\d\d\d' # Matricule de l'ESI
REGEX_MATRICULE = '[a-zA-Z0-9/]+' # Matricule général

from datetime import timedelta

AXES_ENABLED = True
AXES_FAILURE_LIMIT = 3
AXES_LOCK_OUT_AT_FAILURE = True
AXES_COOLOFF_TIME = timedelta(minutes=15)  # Nombre de minutes avant réinitialisation
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']
AXES_RESET_ON_SUCCESS = False

DEV_MODE = True

RECAPTCHA_PUBLIC_KEY = '?'
RECAPTCHA_PRIVATE_KEY = '?'

DATA_UPLOAD_MAX_NUMBER_FIELDS=10000